# Generated by Django 6.0.1 on 2026-01-13 14:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('actor_type', models.CharField(choices=[('service_user', 'Service User'), ('service_provider', 'Service Provider'), ('support', 'Support'), ('regulatory', 'Regulatory')], max_length=50)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Alternative names for this actor')),
                ('function', models.TextField(help_text='Role and significance within the system')),
                ('needs', models.TextField(help_text='Essential services or conditions the actor expects')),
                ('worries', models.TextField(help_text='Main risks, challenges, or adverse conditions')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(choices=[('health', 'Health'), ('education', 'Education'), ('market', 'Market'), ('water', 'Water/WASH'), ('protection', 'Protection'), ('nutrition', 'Nutrition'), ('shelter', 'Shelter'), ('livelihoods', 'Livelihoods')], max_length=50)),
                ('subsector', models.CharField(blank=True, max_length=100)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Systems',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComponentAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goods_services', models.TextField(help_text='Goods/services/resources provided by the actor')),
                ('production', models.IntegerField(help_text='Level of production/throughput (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('replaceability', models.IntegerField(help_text='Level of replaceability (1-5, where 5 = not replaceable)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rationale', models.TextField(help_text='Reason for the assessment scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component_assessment', to='core.actor')),
            ],
            options={
                'verbose_name': 'Component Assessment',
                'verbose_name_plural': 'Component Assessments',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('climate', 'Climate'), ('health', 'Health'), ('economic', 'Economic'), ('conflict', 'Conflict'), ('natural', 'Natural Disaster'), ('political', 'Political')], max_length=50)),
                ('likelihood', models.CharField(choices=[('rare', 'Rare (<10%)'), ('unlikely', 'Unlikely (10-30%)'), ('possible', 'Possible (30-60%)'), ('likely', 'Likely (60-90%)'), ('almost_certain', 'Almost Certain (>90%)')], default='possible', max_length=50)),
                ('historical_occurrences', models.TextField(blank=True, help_text='Years when this risk occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='core.system')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('system', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], default='output', max_length=50)),
                ('goods_services', models.TextField(help_text='Specific goods, services, and/or resources exchanged')),
                ('quality', models.CharField(choices=[('good', 'Good'), ('stressed', 'Stressed'), ('bad', 'Bad'), ('absent', 'Absent')], max_length=50)),
                ('rationale', models.TextField(help_text='Reason for the quality assessment')),
                ('suggested_kpis', models.JSONField(blank=True, default=list, help_text='Suggested key performance indicators')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.actor')),
                ('to_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.actor')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.system')),
            ],
            options={
                'ordering': ['from_actor__name', 'to_actor__name'],
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actors', to='core.system'),
        ),
        migrations.AlterUniqueTogether(
            name='actor',
            unique_together={('system', 'slug')},
        ),
        migrations.CreateModel(
            name='VulnerabilityAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensitivity', models.IntegerField(help_text='How badly the actor is affected (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('exposure', models.IntegerField(help_text='How likely the actor is exposed (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('capacity', models.IntegerField(help_text='Ability to resist/adapt (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rationale', models.TextField(help_text='Reason for the assessment scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_assessments', to='core.actor')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_assessments', to='core.risk')),
            ],
            options={
                'verbose_name': 'Vulnerability Assessment',
                'verbose_name_plural': 'Vulnerability Assessments',
                'unique_together': {('actor', 'risk')},
            },
        ),
    ]
